Various design changes
raulfrk/IncredibleAnimeList pull request #14
Opened 2021-09-17 21:03 UTC by LDalDosso

Update signup button.
Update sidebar routing.
Add email and password errors control.

2021-09-17 21:09 UTC, raulfrk requested changes

2021-09-17 21:09 UTC, raulfrk commented on incredible-frontend/src/LoginForm.js
> +                console.log("Registrato")
The back-end provides with success or error messages such as "A user with this email already exists!". It si recommanded that those are printed instead of a hardly typed one such as "Registrato" or "Registrazione non avvenuta..."

2021-09-18 09:16 UTC, LDalDosso commented on incredible-frontend/src/LoginForm.js
> +                console.log("Registrato")
#15 fix

2021-09-18 09:32 UTC, raulfrk approved these changes

2021-09-18 09:32 UTC, merged